<?php
class Apg_model extends CI_Model {

    public function __construct() {
        parent::__construct();
    }

    public function get_ejes() {
        $sql = ''
			.'select '
            .'distinct on (rnc.registro_nivel_id) '
            .'idit.contenido as id_instrumento, '
			.'ide.contenido as id_eje, '
			.'rnc.contenido as desc_eje  '
			.'from '
			.'"Registro_Nivel_Campo" rnc  '
            .'left join "Registro_Nivel_Campo" idnit on rnc.registro_nivel_id = idnit.registro_nivel_id and idnit.nivel_campo_id = 32 '
			.'left join "Registro_Nivel_Campo" idit on idnit.contenido::int = idit.registro_nivel_id and idit.nivel_id = 2 and idit.nivel_campo_id = 5 '
			.'left join "Registro_Nivel_Campo" ide on rnc.registro_nivel_id = ide.registro_nivel_id and ide.nivel_campo_id = 33 '
			.'where  '
			.'rnc.nivel_id = 8 '
			.'and rnc.nivel_campo_id = 34 '
			.'order by '
            .'rnc.registro_nivel_id, rnc.version desc '
            .'';
        $query = $this->db->query($sql);
        return $query->result_array();
    }

    public function get_lineas() {
        $sql = ''
			.'select '
            .'distinct on (rnc.registro_nivel_id) '
            .'idit.contenido as id_instrumento, '
			.'ide.contenido as id_eje, '
			.'idl.contenido as id_linea, '
			.'rnc.contenido as desc_linea  '
			.'from '
			.'"Registro_Nivel_Campo" rnc  '
            .'left join "Registro_Nivel_Campo" idnit on rnc.registro_nivel_id = idnit.registro_nivel_id and idnit.nivel_campo_id = 35 '
			.'left join "Registro_Nivel_Campo" idit on idnit.contenido::int = idit.registro_nivel_id and idit.nivel_id = 2 and idit.nivel_campo_id = 5 '
			.'left join "Registro_Nivel_Campo" idne on rnc.registro_nivel_id = idne.registro_nivel_id and idne.nivel_campo_id = 36 '
			.'left join "Registro_Nivel_Campo" ide on idne.contenido::int = ide.registro_nivel_id and ide.nivel_id = 8 and ide.nivel_campo_id = 33 '
			.'left join "Registro_Nivel_Campo" idl on rnc.registro_nivel_id = idl.registro_nivel_id and idl.nivel_campo_id = 37 '
			.'where  '
			.'rnc.nivel_id = 9 '
			.'and rnc.nivel_campo_id = 38 '
			.'order by '
            .'rnc.registro_nivel_id, rnc.version desc '
			.'';
        $query = $this->db->query($sql);
        return $query->result_array();
    }

    public function get_objetivos() {
        $sql = ''
            .'select '
            .'distinct on (rnc.registro_nivel_id) '
            .'idit.contenido as id_instrumento, '
            .'ide.contenido as id_eje, '
            .'idl.contenido as id_linea, '
            .'ido.contenido as id_objetivo, '
            .'rnc.contenido as desc_objetivo '
            .'from '
            .'"Registro_Nivel_Campo" rnc  '
            .'left join "Registro_Nivel_Campo" idnit on rnc.registro_nivel_id = idnit.registro_nivel_id and idnit.nivel_campo_id = 39 '
			.'left join "Registro_Nivel_Campo" idit on idnit.contenido::int = idit.registro_nivel_id and idit.nivel_id = 2 and idit.nivel_campo_id = 5 '
            .'left join "Registro_Nivel_Campo" idne on rnc.registro_nivel_id = idne.registro_nivel_id and idne.nivel_campo_id = 40 '
            .'left join "Registro_Nivel_Campo" idnl on rnc.registro_nivel_id = idnl.registro_nivel_id and idnl.nivel_campo_id = 41 '
            .'left join "Registro_Nivel_Campo" ide on idne.contenido::int = ide.registro_nivel_id and ide.nivel_id = 8 and ide. nivel_campo_id = 33 '
            .'left join "Registro_Nivel_Campo" idl on idnl.contenido::int = idl.registro_nivel_id and idl.nivel_id = 9 and idl. nivel_campo_id = 37 '
            .'left join "Registro_Nivel_Campo" ido on rnc.registro_nivel_id = ido.registro_nivel_id and ido.nivel_campo_id = 42 '
            .'where  '
            .'rnc.nivel_id = 10 '
            .'and rnc.nivel_campo_id = 43 '
            .'order by '
            .'rnc.registro_nivel_id, rnc.version desc '
            .'';
        $query = $this->db->query($sql);
        return $query->result_array();
    }

    public function get_estrategias() {
        $sql = ''
            .'select '
            .'distinct on (rnc.registro_nivel_id) '
            .'idit.contenido as id_instrumento, '
            .'ide.contenido as id_eje, '
            .'ido.contenido as id_objetivo, '
            .'ides.contenido as id_estrategia, '
            .'rnc.contenido as desc_estrategia '
            .'from '
            .'"Registro_Nivel_Campo" rnc  '
            .'left join "Registro_Nivel_Campo" idnit on rnc.registro_nivel_id = idnit.registro_nivel_id and idnit.nivel_campo_id = 82 '
			.'left join "Registro_Nivel_Campo" idit on idnit.contenido::int = idit.registro_nivel_id and idit.nivel_id = 2 and idit.nivel_campo_id = 5 '
            .'left join "Registro_Nivel_Campo" idne on rnc.registro_nivel_id = idne.registro_nivel_id and idne.nivel_campo_id = 83 '
            .'left join "Registro_Nivel_Campo" idno on rnc.registro_nivel_id = idno.registro_nivel_id and idno.nivel_campo_id = 84 '
            .'left join "Registro_Nivel_Campo" ide on idne.contenido::int = ide.registro_nivel_id and ide.nivel_id = 8 and ide.nivel_campo_id = 33 '
            .'left join "Registro_Nivel_Campo" ido on idno.contenido::int = ido.registro_nivel_id and ido.nivel_id = 10 and ido.nivel_campo_id = 42 '
            .'left join "Registro_Nivel_Campo" ides on rnc.registro_nivel_id = ides.registro_nivel_id and ides.nivel_campo_id = 85 '
            .'where  '
            .'rnc.nivel_id = 18 '
            .'and rnc.nivel_campo_id = 86 '
            .'order by '
            .'rnc.registro_nivel_id, rnc.version desc '
            .'';
        $query = $this->db->query($sql);
        return $query->result_array();
    }

    public function get_lineas_accion() {
        $sql = ''
            .'select '
            .'distinct on (rnc.registro_nivel_id) '
            .'idit.contenido as id_instrumento, '
            .'ide.contenido as id_eje, '
            .'idl.contenido as id_linea, '
            .'ido.contenido as id_objetivo, '
            .'ides.contenido as id_estrategia, '
            .'idla.contenido as id_linea_accion, '
            .'rnc.contenido as desc_linea_accion '
            .'from '
            .'"Registro_Nivel_Campo" rnc  '
            .'left join "Registro_Nivel_Campo" idnit on rnc.registro_nivel_id = idnit.registro_nivel_id and idnit.nivel_campo_id = 300 '
            .'left join "Registro_Nivel_Campo" idne on rnc.registro_nivel_id = idne.registro_nivel_id and idne.nivel_campo_id = 301 '
            .'left join "Registro_Nivel_Campo" idnl on rnc.registro_nivel_id = idnl.registro_nivel_id and idnl.nivel_campo_id = 302 '
            .'left join "Registro_Nivel_Campo" idno on rnc.registro_nivel_id = idno.registro_nivel_id and idno.nivel_campo_id = 303 '
            .'left join "Registro_Nivel_Campo" idnes on rnc.registro_nivel_id = idnes.registro_nivel_id and idnes.nivel_campo_id = 304 '
            .'left join "Registro_Nivel_Campo" idit on idnit.contenido::int = idit.registro_nivel_id and idit.nivel_id = 2 and idit.nivel_campo_id = 5 '
            .'left join "Registro_Nivel_Campo" ide on idne.contenido::int = ide.registro_nivel_id and ide.nivel_id = 8 and ide.nivel_campo_id = 33 '
            .'left join "Registro_Nivel_Campo" idl on idnl.contenido::int = idl.registro_nivel_id and idl.nivel_id = 9 and idl. nivel_campo_id = 37 '
            .'left join "Registro_Nivel_Campo" ido on idno.contenido::int = ido.registro_nivel_id and ido.nivel_id = 10 and ido.nivel_campo_id = 42 '
            .'left join "Registro_Nivel_Campo" ides on idnes.contenido::int = ides.registro_nivel_id and ides.nivel_id = 18 and ides.nivel_campo_id = 85 '
            .'left join "Registro_Nivel_Campo" idla on rnc.registro_nivel_id = idla.registro_nivel_id and idla.nivel_campo_id = 305 '
            .'where  '
            .'rnc.nivel_id = 55 '
            .'and rnc.nivel_campo_id = 306 '
            .'order by '
            .'rnc.registro_nivel_id, rnc.version desc '
            .'';
        $query = $this->db->query($sql);
        return $query->result_array();
    }

    public function get_indicadores() {
        $sql = ''
            .'select '
            .'distinct on (rnc.registro_nivel_id) '
            .'idit.contenido as id_instrumento, '
            .'ide.contenido as id_eje, '
            .'idl.contenido as id_linea, '
            .'ido.contenido as id_objetivo, '
            .'idi.contenido as id_indicador, '
            .'rnc.contenido as desc_indicador '
            .'from '
            .'"Registro_Nivel_Campo" rnc  '
            .'left join "Registro_Nivel_Campo" idnit on rnc.registro_nivel_id = idnit.registro_nivel_id and idnit.nivel_campo_id = 44 '
			.'left join "Registro_Nivel_Campo" idit on idnit.contenido::int = idit.registro_nivel_id and idit.nivel_id = 2 and idit.nivel_campo_id = 5 '
            .'left join "Registro_Nivel_Campo" idne on rnc.registro_nivel_id = idne.registro_nivel_id and idne.nivel_campo_id = 45 '
            .'left join "Registro_Nivel_Campo" idnl on rnc.registro_nivel_id = idnl.registro_nivel_id and idnl.nivel_campo_id = 46 '
            .'left join "Registro_Nivel_Campo" idno on rnc.registro_nivel_id = idno.registro_nivel_id and idno.nivel_campo_id = 47 '
            .'left join "Registro_Nivel_Campo" ide on idne.contenido::int = ide.registro_nivel_id and ide.nivel_id = 8 and ide.nivel_campo_id = 33 '
            .'left join "Registro_Nivel_Campo" idl on idnl.contenido::int = idl.registro_nivel_id and idl.nivel_id = 9 and idl. nivel_campo_id = 37 '
            .'left join "Registro_Nivel_Campo" ido on idno.contenido::int = ido.registro_nivel_id and ido.nivel_id = 10 and ido.nivel_campo_id = 42 '
            .'left join "Registro_Nivel_Campo" idi on rnc.registro_nivel_id = idi.registro_nivel_id and idi.nivel_campo_id = 48 '
            .'where  '
            .'rnc.nivel_id = 11 '
            .'and rnc.nivel_campo_id = 49 '
            .'order by '
            .'rnc.registro_nivel_id, rnc.version desc '
            .'';
        $query = $this->db->query($sql);
        return $query->result_array();
    }

    public function get_metas() {
        $sql = ''
            .'select '
            .'distinct on (rnc.registro_nivel_id) '
            .'idit.contenido as id_instrumento, '
            .'ide.contenido as id_eje, '
            .'idl.contenido as id_linea, '
            .'ido.contenido as id_objetivo, '
            .'idi.contenido as id_indicador, '
            .'idm.contenido as id_meta, '
            .'rnc.contenido as desc_meta '
            .'from '
            .'"Registro_Nivel_Campo" rnc  '
            .'left join "Registro_Nivel_Campo" idnit on rnc.registro_nivel_id = idnit.registro_nivel_id and idnit.nivel_campo_id = 50 '
			.'left join "Registro_Nivel_Campo" idit on idnit.contenido::int = idit.registro_nivel_id and idit.nivel_id = 2 and idit.nivel_campo_id = 5 '
            .'left join "Registro_Nivel_Campo" idne on rnc.registro_nivel_id = idne.registro_nivel_id and idne.nivel_campo_id = 51 '
            .'left join "Registro_Nivel_Campo" idnl on rnc.registro_nivel_id = idnl.registro_nivel_id and idnl.nivel_campo_id = 52 '
            .'left join "Registro_Nivel_Campo" idno on rnc.registro_nivel_id = idno.registro_nivel_id and idno.nivel_campo_id = 53 '
            .'left join "Registro_Nivel_Campo" idni on rnc.registro_nivel_id = idni.registro_nivel_id and idni.nivel_campo_id = 54 '
            .'left join "Registro_Nivel_Campo" ide on idne.contenido::int = ide.registro_nivel_id and ide.nivel_id = 8 and ide.nivel_campo_id = 33 '
            .'left join "Registro_Nivel_Campo" idl on idnl.contenido::int = idl.registro_nivel_id and idl.nivel_id = 9 and idl. nivel_campo_id = 37 '
            .'left join "Registro_Nivel_Campo" ido on idno.contenido::int = ido.registro_nivel_id and ido.nivel_id = 10 and ido.nivel_campo_id = 42 '
            .'left join "Registro_Nivel_Campo" idi on idni.contenido::int = idi.registro_nivel_id and idi.nivel_id = 11 and idi.nivel_campo_id = 48 '
            .'left join "Registro_Nivel_Campo" idm on rnc.registro_nivel_id = idm.registro_nivel_id and idm.nivel_campo_id = 55 '
            .'where  '
            .'rnc.nivel_id = 12 '
            .'and rnc.nivel_campo_id = 56 '
            .'order by '
            .'rnc.registro_nivel_id, rnc.version desc '
            .'';
        $query = $this->db->query($sql);
        return $query->result_array();
    }

    public function get_ftis() {
        $sql = ''
            .'select '
            .'distinct on (rnc.registro_nivel_id) '
            .'id_indicador.contenido as id_indicador, '
            .'id_instrumento.contenido as id_instrumento, '
            .'id_eje.contenido as id_eje, '
            .'id_linea.contenido as id_linea, '
            .'id_objetivo.contenido as id_objetivo, '
            .'id_objetivo_ods.contenido as id_objetivo_ods, '
            .'id_meta_ods.contenido as id_meta_ods, '
            .'desc_impacto_esperado.contenido as desc_impacto_esperado, '
            .'funcionario.contenido as funcionario, '
            .'telefono.contenido as telefono, '
            .'correo.contenido as correo, '
            .'dimension.contenido as dimension, '
            .'nivel.contenido as nivel, '
            .'definicion_indicador.contenido as definicion_indicador, '
            .'importancia_indicador.contenido as importancia_indicador, '
            .'unidad_medida_indicador.contenido as unidad_medida_indicador, '
            .'algoritmo.contenido as algoritmo, '
            .'tipo_indicador.contenido as tipo_indicador, '
            .'frecuencia_medicion.contenido as frecuencia_medicion, '
            .'metodo_calculo.contenido as metodo_calculo, '
            .'unidad_medida_indicador.contenido as unidad_medida_indicador, '
            .'algoritmo.contenido as algoritmo, '
            .'tipo_indicador.contenido as tipo_indicador, '
            .'frecuencia_medicion.contenido as frecuencia_medicion, '
            .'metodo_calculo.contenido as metodo_calculo, '
            .'sentido_indicador.contenido as sentido_indicador, '
            .'acumulado.contenido as acumulado, '
            .'fecha_disponib_info.contenido as fecha_disponib_info, '
            .'anio_linea_base.contenido as anio_linea_base, '
            .'valor_linea_base.contenido as valor_linea_base, '
            .'nombre_a.contenido as nombre_a, '
            .'unidad_medida_a.contenido as unidad_medida_a, '
            .'descripcion_a.contenido as descripcion_a, '
            .'sobre_demanda_a.contenido as sobre_demanda_a, '
            .'nombre_b.contenido as nombre_b, '
            .'unidad_medida_b.contenido as unidad_medida_b, '
            .'descripcion_b.contenido as descripcion_b, '
            .'sobre_demanda_b.contenido as sobre_demanda_b, '
            .'valor_a_2018.contenido as valor_a_2018, '
            .'valor_a_2019.contenido as valor_a_2019, '
            .'valor_a_2020.contenido as valor_a_2020, '
            .'valor_a_2021.contenido as valor_a_2021, '
            .'valor_a_2022.contenido as valor_a_2022, '
            .'valor_a_2023.contenido as valor_a_2023, '
            .'valor_a_2024.contenido as valor_a_2024, '
            .'valor_b_2018.contenido as valor_b_2018, '
            .'valor_b_2019.contenido as valor_b_2019, '
            .'valor_b_2020.contenido as valor_b_2020, '
            .'valor_b_2021.contenido as valor_b_2021, '
            .'valor_b_2022.contenido as valor_b_2022, '
            .'valor_b_2023.contenido as valor_b_2023, '
            .'valor_b_2024.contenido as valor_b_2024, '
            .'meta_anual_2018.contenido as meta_anual_2018, '
            .'meta_anual_2019.contenido as meta_anual_2019, '
            .'meta_anual_2020.contenido as meta_anual_2020, '
            .'meta_anual_2021.contenido as meta_anual_2021, '
            .'meta_anual_2022.contenido as meta_anual_2022, '
            .'meta_anual_2023.contenido as meta_anual_2023, '
            .'meta_anual_2024.contenido as meta_anual_2024 '
            .'from '
            .'"Registro_Nivel_Campo" rnc  '
            .'left join "Registro_Nivel_Campo" idn_instrumento on rnc.registro_nivel_id = idn_instrumento.registro_nivel_id and idn_instrumento.nivel_campo_id = 157 '
            .'left join "Registro_Nivel_Campo" idn_eje on rnc.registro_nivel_id = idn_eje.registro_nivel_id and idn_eje.nivel_campo_id = 158 '
            .'left join "Registro_Nivel_Campo" idn_linea on rnc.registro_nivel_id = idn_linea.registro_nivel_id and idn_linea.nivel_campo_id = 159 '
            .'left join "Registro_Nivel_Campo" idn_objetivo on rnc.registro_nivel_id = idn_objetivo.registro_nivel_id and idn_objetivo.nivel_campo_id = 120 '
            .'left join "Registro_Nivel_Campo" idn_objetivo_ods on rnc.registro_nivel_id = idn_objetivo_ods.registro_nivel_id and idn_objetivo_ods.nivel_campo_id = 121 '
            .'left join "Registro_Nivel_Campo" idn_meta_ods on rnc.registro_nivel_id = idn_meta_ods.registro_nivel_id and idn_meta_ods.nivel_campo_id = 195 '
            .'left join "Registro_Nivel_Campo" idn_dimension on rnc.registro_nivel_id = idn_dimension.registro_nivel_id and idn_dimension.nivel_campo_id = 130 '
            .'left join "Registro_Nivel_Campo" idn_nivel on rnc.registro_nivel_id = idn_nivel.registro_nivel_id and idn_nivel.nivel_campo_id = 131 '
            .'left join "Registro_Nivel_Campo" idn_algoritmo on rnc.registro_nivel_id = idn_algoritmo.registro_nivel_id and idn_algoritmo.nivel_campo_id = 140 '
            .'left join "Registro_Nivel_Campo" idn_tipo_indicador on rnc.registro_nivel_id = idn_tipo_indicador.registro_nivel_id and idn_tipo_indicador.nivel_campo_id = 141 '
            .'left join "Registro_Nivel_Campo" idn_frecuencia_medicion on rnc.registro_nivel_id = idn_frecuencia_medicion.registro_nivel_id and idn_frecuencia_medicion.nivel_campo_id = 142 '
            .'left join "Registro_Nivel_Campo" idn_metodo_calculo on rnc.registro_nivel_id = idn_metodo_calculo.registro_nivel_id and idn_metodo_calculo.nivel_campo_id = 143 '
            .'left join "Registro_Nivel_Campo" id_indicador on rnc.contenido::int = id_indicador.registro_nivel_id and id_indicador.nivel_id = 11 and id_indicador.nivel_campo_id = 48 '
            .'left join "Registro_Nivel_Campo" id_instrumento on idn_instrumento.contenido::int = id_instrumento.registro_nivel_id and id_instrumento.nivel_id = 2 and id_instrumento.nivel_campo_id = 5 '
            .'left join "Registro_Nivel_Campo" id_eje on idn_eje.contenido::int = id_eje.registro_nivel_id and id_eje.nivel_id = 8 and id_eje.nivel_campo_id = 33 '
            .'left join "Registro_Nivel_Campo" id_linea on idn_linea.contenido::int = id_linea.registro_nivel_id and id_linea.nivel_id = 9 and id_linea.nivel_campo_id = 37 '
            .'left join "Registro_Nivel_Campo" id_objetivo on idn_objetivo.contenido::int = id_objetivo.registro_nivel_id and id_objetivo.nivel_id = 10 and id_objetivo.nivel_campo_id = 42 '
            .'left join "Registro_Nivel_Campo" id_objetivo_ods on idn_objetivo_ods.contenido::int = id_objetivo_ods.registro_nivel_id and id_objetivo_ods.nivel_id = 23 and id_objetivo_ods.nivel_campo_id = 105 '
            .'left join "Registro_Nivel_Campo" id_meta_ods on idn_meta_ods.contenido::int = id_meta_ods.registro_nivel_id and id_meta_ods.nivel_id = 33 and id_meta_ods.nivel_campo_id = 193 '
            .'left join "Registro_Nivel_Campo" desc_impacto_esperado on rnc.registro_nivel_id = desc_impacto_esperado.registro_nivel_id and desc_impacto_esperado.nivel_campo_id = 122 '
            .'left join "Registro_Nivel_Campo" definicion_indicador on rnc.registro_nivel_id = definicion_indicador.registro_nivel_id and definicion_indicador.nivel_campo_id = 132 '
            .'left join "Registro_Nivel_Campo" importancia_indicador on rnc.registro_nivel_id = importancia_indicador.registro_nivel_id and importancia_indicador.nivel_campo_id = 133 '
            .'left join "Registro_Nivel_Campo" unidad_medida_indicador on rnc.registro_nivel_id = unidad_medida_indicador.registro_nivel_id and unidad_medida_indicador.nivel_campo_id = 134 '
            .'left join "Registro_Nivel_Campo" funcionario on rnc.registro_nivel_id = funcionario.registro_nivel_id and funcionario.nivel_campo_id = 123 '
            .'left join "Registro_Nivel_Campo" telefono on rnc.registro_nivel_id = telefono.registro_nivel_id and telefono.nivel_campo_id = 124 '
            .'left join "Registro_Nivel_Campo" correo on rnc.registro_nivel_id = correo.registro_nivel_id and correo.nivel_campo_id = 125 '
            .'left join "Registro_Nivel_Campo" dimension on idn_dimension.contenido::int = dimension.registro_nivel_id and dimension.nivel_id = 27 and dimension.nivel_campo_id = 128 '
            .'left join "Registro_Nivel_Campo" nivel on idn_nivel.contenido::int = nivel.registro_nivel_id and nivel.nivel_id = 28 and nivel.nivel_campo_id = 129 '
            .'left join "Registro_Nivel_Campo" algoritmo on idn_algoritmo.contenido::int = algoritmo.registro_nivel_id and algoritmo.nivel_id = 29 and algoritmo.nivel_campo_id = 136 '
            .'left join "Registro_Nivel_Campo" tipo_indicador on idn_tipo_indicador.contenido::int = tipo_indicador.registro_nivel_id and tipo_indicador.nivel_id = 30 and tipo_indicador.nivel_campo_id = 137 '
            .'left join "Registro_Nivel_Campo" frecuencia_medicion on idn_frecuencia_medicion.contenido::int = frecuencia_medicion.registro_nivel_id and frecuencia_medicion.nivel_id = 31 and frecuencia_medicion.nivel_campo_id = 138 '
            .'left join "Registro_Nivel_Campo" metodo_calculo on idn_metodo_calculo.contenido::int = metodo_calculo.registro_nivel_id and metodo_calculo.nivel_id = 32 and metodo_calculo.nivel_campo_id = 139 '
            .'left join "Registro_Nivel_Campo" sentido_indicador on rnc.registro_nivel_id = sentido_indicador.registro_nivel_id and sentido_indicador.nivel_campo_id = 144 '
            .'left join "Registro_Nivel_Campo" acumulado on rnc.registro_nivel_id = acumulado.registro_nivel_id and acumulado.nivel_campo_id = 145 '
            .'left join "Registro_Nivel_Campo" fecha_disponib_info on rnc.registro_nivel_id = fecha_disponib_info.registro_nivel_id and fecha_disponib_info.nivel_campo_id = 146 '
            .'left join "Registro_Nivel_Campo" anio_linea_base on rnc.registro_nivel_id = anio_linea_base.registro_nivel_id and anio_linea_base.nivel_campo_id = 148 '
            .'left join "Registro_Nivel_Campo" valor_linea_base on rnc.registro_nivel_id = valor_linea_base.registro_nivel_id and valor_linea_base.nivel_campo_id = 149 '
            .'left join "Registro_Nivel_Campo" nombre_a on rnc.registro_nivel_id = nombre_a.registro_nivel_id and nombre_a.nivel_campo_id = 175 '
            .'left join "Registro_Nivel_Campo" unidad_medida_a on rnc.registro_nivel_id = unidad_medida_a.registro_nivel_id and unidad_medida_a.nivel_campo_id = 176 '
            .'left join "Registro_Nivel_Campo" descripcion_a on rnc.registro_nivel_id = descripcion_a.registro_nivel_id and descripcion_a.nivel_campo_id = 177 '
            .'left join "Registro_Nivel_Campo" sobre_demanda_a on rnc.registro_nivel_id = sobre_demanda_a.registro_nivel_id and sobre_demanda_a.nivel_campo_id = 178 '
            .'left join "Registro_Nivel_Campo" nombre_b on rnc.registro_nivel_id = nombre_b.registro_nivel_id and nombre_b.nivel_campo_id = 180 '
            .'left join "Registro_Nivel_Campo" unidad_medida_b on rnc.registro_nivel_id = unidad_medida_b.registro_nivel_id and unidad_medida_b.nivel_campo_id = 181 '
            .'left join "Registro_Nivel_Campo" descripcion_b on rnc.registro_nivel_id = descripcion_b.registro_nivel_id and descripcion_b.nivel_campo_id = 182 '
            .'left join "Registro_Nivel_Campo" sobre_demanda_b on rnc.registro_nivel_id = sobre_demanda_b.registro_nivel_id and sobre_demanda_b.nivel_campo_id = 183 '
            .'left join "Registro_Nivel_Campo" valor_a_2018 on rnc.registro_nivel_id = valor_a_2018.registro_nivel_id and valor_a_2018.nivel_campo_id = 168 '
            .'left join "Registro_Nivel_Campo" valor_a_2019 on rnc.registro_nivel_id = valor_a_2019.registro_nivel_id and valor_a_2019.nivel_campo_id = 169 '
            .'left join "Registro_Nivel_Campo" valor_a_2020 on rnc.registro_nivel_id = valor_a_2020.registro_nivel_id and valor_a_2020.nivel_campo_id = 170 '
            .'left join "Registro_Nivel_Campo" valor_a_2021 on rnc.registro_nivel_id = valor_a_2021.registro_nivel_id and valor_a_2021.nivel_campo_id = 171 '
            .'left join "Registro_Nivel_Campo" valor_a_2022 on rnc.registro_nivel_id = valor_a_2022.registro_nivel_id and valor_a_2022.nivel_campo_id = 172 '
            .'left join "Registro_Nivel_Campo" valor_a_2023 on rnc.registro_nivel_id = valor_a_2023.registro_nivel_id and valor_a_2023.nivel_campo_id = 173 '
            .'left join "Registro_Nivel_Campo" valor_a_2024 on rnc.registro_nivel_id = valor_a_2024.registro_nivel_id and valor_a_2024.nivel_campo_id = 174 '
            .'left join "Registro_Nivel_Campo" valor_b_2018 on rnc.registro_nivel_id = valor_b_2018.registro_nivel_id and valor_b_2018.nivel_campo_id = 161 '
            .'left join "Registro_Nivel_Campo" valor_b_2019 on rnc.registro_nivel_id = valor_b_2019.registro_nivel_id and valor_b_2019.nivel_campo_id = 162 '
            .'left join "Registro_Nivel_Campo" valor_b_2020 on rnc.registro_nivel_id = valor_b_2020.registro_nivel_id and valor_b_2020.nivel_campo_id = 163 '
            .'left join "Registro_Nivel_Campo" valor_b_2021 on rnc.registro_nivel_id = valor_b_2021.registro_nivel_id and valor_b_2021.nivel_campo_id = 164 '
            .'left join "Registro_Nivel_Campo" valor_b_2022 on rnc.registro_nivel_id = valor_b_2022.registro_nivel_id and valor_b_2022.nivel_campo_id = 165 '
            .'left join "Registro_Nivel_Campo" valor_b_2023 on rnc.registro_nivel_id = valor_b_2023.registro_nivel_id and valor_b_2023.nivel_campo_id = 166 '
            .'left join "Registro_Nivel_Campo" valor_b_2024 on rnc.registro_nivel_id = valor_b_2024.registro_nivel_id and valor_b_2024.nivel_campo_id = 167 '
            .'left join "Registro_Nivel_Campo" meta_anual_2018 on rnc.registro_nivel_id = meta_anual_2018.registro_nivel_id and meta_anual_2018.nivel_campo_id = 185 '
            .'left join "Registro_Nivel_Campo" meta_anual_2019 on rnc.registro_nivel_id = meta_anual_2019.registro_nivel_id and meta_anual_2019.nivel_campo_id = 186 '
            .'left join "Registro_Nivel_Campo" meta_anual_2020 on rnc.registro_nivel_id = meta_anual_2020.registro_nivel_id and meta_anual_2020.nivel_campo_id = 187 '
            .'left join "Registro_Nivel_Campo" meta_anual_2021 on rnc.registro_nivel_id = meta_anual_2021.registro_nivel_id and meta_anual_2021.nivel_campo_id = 188 '
            .'left join "Registro_Nivel_Campo" meta_anual_2022 on rnc.registro_nivel_id = meta_anual_2022.registro_nivel_id and meta_anual_2022.nivel_campo_id = 189 '
            .'left join "Registro_Nivel_Campo" meta_anual_2023 on rnc.registro_nivel_id = meta_anual_2023.registro_nivel_id and meta_anual_2023.nivel_campo_id = 190 '
            .'left join "Registro_Nivel_Campo" meta_anual_2024 on rnc.registro_nivel_id = meta_anual_2024.registro_nivel_id and meta_anual_2024.nivel_campo_id = 191 '
            .'where  '
            .'rnc.nivel_id = 26 '
            .'and rnc.nivel_campo_id = 160 '
            .'order by '
            .'rnc.registro_nivel_id, rnc.version desc '
            .'';
        $query = $this->db->query($sql);
        return $query->result_array();
    }

}
